- name: wipe web_app
  tags: [web_app_wipe]
  when: web_app_full_wipe
  block:
    - name: check if docker-compose exists
      ansible.builtin.stat:
        path: '{{web_app_dir}}/docker-compose.yml'
      register: web_app_compose
    - name: check if web app directory exists
      ansible.builtin.stat:
        path: '{{web_app_dir}}'
      register: web_app_dir
    - name: Docker compose rm
      when: web_app_compose.stat.exists
      community.docker.docker_compose:
        project_src: '{{web_app_dir}}'
        state: absent
        remove_orphans: true
        remove_images: all
        remove_volumes: true
    - name: rmdir {{web_app_dir}}
      when: web_app_dir.stat.exists
      ansible.builtin.file:
        path: '{{web_app_dir}}'
        state: absent