version: '3.9'

services:

  app_python:
    image: glebsmetanin/moscow_time:latest
    mem_limit: 150m
    ports:
      - 5000:5000
    logging:
      driver: "json-file"
      options:
        tag: "{{.ImageName}}|{{.Name}}"

  loki:
    container_name: monitoring.loki
    image: grafana/loki:2.6.1
    mem_limit: 150m
    expose:
      - 3100
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
    logging:
      driver: "json-file"
      options:
        tag: "{{.ImageName}}|{{.Name}}"

  promtail:
    image: grafana/promtail:2.6.1
    mem_limit: 150m
    container_name: monitoring.promtail
    expose:
      - 9080
    ports:
      - "9080:9080"
    volumes:
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - promtail-data:/var/lib/promtail/positions
      - './promtail.yaml:/etc/promtail/promtail.yaml'
    command: -config.file=/etc/promtail/promtail.yaml
    restart: unless-stopped
    labels:
      org.label-schema.group: "monitoring"
    logging:
      driver: "json-file"
      options:
        tag: "{{.ImageName}}|{{.Name}}"

  prometheus:
    image: prom/prometheus
    mem_limit: 150m
    volumes:
      - './prometheus.yml:/etc/prometheus/prometheus.yml'
      - prometheus-data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    ports:
      - "9090:9090"

  grafana:
    image: grafana/grafana:latest
    mem_limit: 150m
    container_name: monitoring.grafana
    volumes:
      - './datasources/loki.yaml:/etc/grafana/provisioning/datasources/loki_ds.yaml'
      - './datasources/prometheus.yml:/etc/grafana/provisioning/datasources/prometheus_ds.yml'
    environment:
      - GF_SECURITY_ADMIN_USER=${ADMIN_USER:-admin}
      - GF_SECURITY_ADMIN_PASSWORD=${ADMIN_PASSWORD:-admin}
      - GF_PATHS_PROVISIONING=/etc/grafana/provisioning
    expose:
      - 3000
    ports:
      - "3000:3000"
    logging:
      driver: "json-file"
      options:
        tag: "{{.ImageName}}|{{.Name}}"

volumes:
  promtail-data: {}
  prometheus-data: {}
